
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-toolchains
  namespace: demo
  labels:
    app: test-app-toolchains
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-toolchains
  template:
    metadata:
      labels:
        app: test-app-toolchains
    spec:
      containers:
        - name: test-app-toolchains
          image: us.icr.io/topicos-sprintstage/test-app-toolchains
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-toolchains
  namespace: demo
spec:
  type: NodePort
  selector:
    app: test-app-toolchains
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001 #Entre 30000 - 32768
---
apiVersion: v1
kind: Route
metadata:
    name: test-app-toolchains
    namespace: demo
spec:
    to:
        kind: Service
        name: test-app-toolchains